### ISSUE TITLE
runtime failure

### ISSUE THREAD

**Issue by nathanieltagg** [chdemko/pandoc-latex-color#7]
No idea where to start on this; I don't use "Caption" anywhere.
```
 $ pandoc --mathjax  hw01.tex -t html5 -s -o hw01.html --extract-media=html --filter pandoc-latex-color
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-latex-color", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pandoc_latex_color.py", line 345, in main
    return run_filter(colorize, prepare=prepare, finalize=finalize, doc=doc)
  File "/usr/local/lib/python3.7/site-packages/panflute/io.py", line 260, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/panflute/io.py", line 233, in run_filters
    doc = load(input_stream=input_stream)
  File "/usr/local/lib/python3.7/site-packages/panflute/io.py", line 56, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/local/lib/python3.7/site-packages/panflute/elements.py", line 1478, in from_json
    raise Exception('unknown tag: ' + tag)
Exception: unknown tag: Caption
Error running filter pandoc-latex-color:
Filter returned error status 1
```

**Comment by chdemko** [comment]
See https://github.com/sergiocorreia/panflute/issues/142

**Comment by chdemko** [comment]
See https://github.com/sergiocorreia/panflute/issues/142
